Improve Gerrit icon
SanderRonde/VSCode-Gerrit pull request #75
Opened 2024-07-09 23:17 UTC by felipecrs

SVG was taken from https://en.m.wikipedia.org/wiki/File:Gerrit_icon.svg, and pretty-formatted with the XML extension for VS Code.

Then, I used the following tool to generate the PNG in 256x256 which is the size [recommended by VS Code](https://code.visualstudio.com/api/references/extension-manifest).

https://vincerubinetti.github.io/svg-to-png/

2024-07-14 13:12 UTC, SanderRonde commented
Thanks for the PR! The PNG size upgrade is a good change, let's keep that one. But the svg change will actually make the icon look really weird in VSCode (see image below). VSCode turns the colored in SVG into a greyscale one with only filled-in or transparant. The red and green then also turn into grey turning it into a square blob. If you can remove that part of the change from this PR it's all good!
![image](https://github.com/user-attachments/assets/98e7d2f8-1da2-4156-94c5-cd1d06f67615)

2024-07-14 23:52 UTC, felipecrs commented
You are totally right. I'll see what I can do, otherwise I'll restore the original SVG.

2024-07-15 14:20 UTC, felipecrs commented
I restored the original icon, but pretty-printed it with the [SVG extension](https://marketplace.visualstudio.com/items?itemName=jock.svg).

I noticed a very small issue with it:

![image](https://github.com/user-attachments/assets/df284702-e871-45f7-bdda-620521e7bcdd)

But I could not fix it, I don't know anything about SVGs lol.

2024-07-15 14:24 UTC, SanderRonde requested changes

2024-07-15 14:24 UTC, SanderRonde commented on vscode--gerrit-1.2.34.zip
Oh wow did I commit this one. thanks for removing it

2024-07-15 14:24 UTC, SanderRonde commented on yarn.lock
This one was actually intentional, it makes the git diff a bit more readable (see [bun docs](https://bun.sh/docs/install/lockfile))

2024-07-15 14:25 UTC, SanderRonde commented
Ah the little bit of space between the svg is fine, you won't see it anyways since it's so tiny. So if you restore the `yarn.lock` file all good

2024-07-15 14:27 UTC, felipecrs commented on yarn.lock
Oh, got it. I restored it and forcefully set vscode to use bun, otherwise:

![image](https://github.com/user-attachments/assets/5d333213-6c02-4e11-9af0-1960506a64eb)

2024-07-15 14:28 UTC, felipecrs commented
> Ah the little bit of space between the svg is fine, you won't see it anyways since it's so tiny. So if you restore the `yarn.lock` file all good

I actually fixed it in https://github.com/SanderRonde/VSCode-Gerrit/pull/75/commits/acf6609737da3af96266f12641777072d9f55709.

2024-07-15 14:30 UTC, felipecrs commented on yarn.lock
PS: I just noticed you did the same thing too on main branch. Restored it now.

2024-07-15 14:40 UTC, SanderRonde approved these changes

2024-07-15 14:41 UTC, SanderRonde commented
Awesome, thanks for the PR! Will merge it as soon as you fix the merge conflicts :)

2024-07-15 14:42 UTC, felipecrs commented
> Awesome, thanks for the PR! Will merge it as soon as you fix the merge conflicts :)

Hm... I had fixed already, I believe.

![image](https://github.com/user-attachments/assets/74c60e27-d8eb-4abb-9012-f4220adc06e8)

2024-07-15 14:44 UTC, SanderRonde commented
![image](https://github.com/user-attachments/assets/69f2f066-c2ce-4e3c-a5ca-cefef9a2ff8d)

Oh weird github is showing me something else. I'll try and fix it

2024-07-15 14:45 UTC, merged

2024-07-15 14:45 UTC, SanderRonde commented
Ah it was the rebasing, a merge commit was fine. Thanks again for the PR!